### ISSUE TITLE
Have a look at brfs

### ISSUE THREAD

**Issue by thlorenz** [ScottWeinstein/requiredetextify#1]
Judging from the name what you are up to, I'd guess that [brfs](https://github.com/substack/brfs) may already solve your problem?

BTW [here](https://github.com/substack/node-browserify/wiki/list-of-transforms) is a list of existing transforms.
The [wiki](https://github.com/substack/node-browserify/wiki) has other browserify related goodies.

**Comment by ScottWeinstein** [comment]
Almost. The need is to simultaneously support AMD/requirejs and browserify.

**Comment by thlorenz** [comment]
Ah, yeah UMD is supposed to solve that I think, but never tried that.
But looks like your use case is even different.
